name: TK-TODO Check  # IGNORE:TK

on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: read

jobs:
  tk-todo-check:  # IGNORE:TK
    name: Check for TK-TODO markers  # IGNORE:TK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Check for TK-TODO markers  # IGNORE:TK
        uses: aaronsteers/tk-todo-check-action@382e4a88feebf47feae8495a82fe62268c69aeb3 # v1.0.0 IGNORE:TK
